# http://blog.bleything.net/2006/06/27/dry-out-your-database-yml
login: &login
  adapter: mysql
  username: root
  password: ADD_ME
  host: localhost

development:
  <<: *login
  database: ronin_development

test:
  <<: *login
  database: ronin_test

production:
  <<: *login
  database: ronin_production
